#!/bin/bash
#this is a simple script that reads off system information and system status and gives it to the user.

echo "System Report for $HOSTNAME generated by $USERNAME, on $DATETIME"
 
echo "System Information"
echo "------------------"

HOSTNAME=$(hostname) #gets the system hostname for the script first line
USERNAME=$(whoami) #gets the system user for the script first line
DATETIME=$(date) #gets the current date for the script first line

source /etc/os-release #gets information about the system
OS="$NAME $VERSION" #puts Name and version into OS variable

UPTIME=$(uptime -p) #shows how long the systems uptime has been

CPU=$(lshw -class processor 2>/dev/null | grep "product" | head -n 1 | cut -d ':' -f2 | xargs)
#gets the Cpu model

RAM=$(free -h | awk '/^Mem:/ {print $2}')
#gets the total installed ram in the VM

DISKS=$(lsblk -bdno SIZE | awk '{s+=$1} END {printf "%.1fG", s/1024/1024/1024}')
#Gets the total size of the installed disk

VIDEO=$(lshw -class display 2>/dev/null | grep "product" | head -n 1 | cut -d ':' -f2 | xargs)
#gets the video card model

HOST_IP=$(ip route get 1.1.1.1 | awk '/src/ {print $NF}')
#gets the Ip address

GATEWAY=$(ip route | grep default | awk '{print $3}')
#gets the router gateway IP

DNS=$(grep nameserver /etc/resolv.conf | head -n 1 | awk '{print $2}')
#Gets the DNS Server

USERS=$(who | awk '{print $1}' | sort | uniq | paste -sd ',' -)
#Gets all users who are currently logged in

DISKSPACE=$(df -h / | awk 'NR==2 {print $4}')
#gets the avalable diskspace in the system

PROCESSES=$(ps aux | wc -l)
#Counts the total number of processes  running on the system

LOAD=$(uptime | awk -F'load average:' '{print $2}' | xargs)
#shows the CPU usage

PORTS=$(ss -tuln | awk '/LISTEN/ {print $5}' | awk -F: '{print $NF}' | sort -n | uniq | paste -sd ', ' -)
#gets the network ports the system is useing

UFW=$(sudo ufw status | head -n 1)
#gets weather the firewall is actve or not.

#The following echo commands display the acutaly information by using the variable
#and giving context as to what its displaying.

echo ""
echo "System Information"
echo ""
echo "OS: $OS"
echo "Uptime: $UPTIME"
echo "CPU: $CPU"      #echo cpu should go CPU: then display the vaiaable information stored in $CPU.
echo "RAM: $RAM"
echo "Disk(s): $DISKS"
echo "Video: $VIDEO"
echo "Host Address: $HOST_IP"
echo "Gateway IP: $GATEWAY"
echo "DNS Server: $DNS"
echo ""

echo "System Status"
echo ""
echo "Users Logged In: $USERS"
echo "Disk Space: $DISKSPACE"
echo "Process Count: $PROCESSES"
echo "Load Averages: $LOAD"
echo "Listening Network Ports: $PORTS"
echo "UFW Status: $UFW"
echo ""
